import os
from dotenv import load_dotenv
load_dotenv()

AWS_ACCESS_KEY_ID = os.getenv("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = os.getenv("AWS_SECRET_ACCESS_KEY")
AWS_REGION = os.getenv("AWS_REGION")
S3_BUCKET_NAME = os.getenv("S3_BUCKET_NAME")
PINECONE_INDEX_NAME=os.getenv("PINECONE_INDEX_NAME")
PINECONE_API_KEY=os.getenv("PINECONE_API_KEY")
PINECONE_ENVIORNMENT=os.getenv("PINECONE_ENVIORNMENT")
PINECONE_DIMENSIONS=os.getenv("PINECONE_DIMENSIONS")
